# Generated by Django 4.1.5 on 2023-01-06 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=150, verbose_name='Название шаблона')),
            ],
        ),
        migrations.CreateModel(
            name='FieldForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=150, verbose_name='Название поля')),
                ('field_type', models.CharField(choices=[('email', 'email'), ('phone', 'phone'), ('date', 'date'), ('text', 'text')], max_length=5, verbose_name='Тип поля')),
                ('template_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_fields', to='definition_form.templateform', verbose_name='Шаблон формы')),
            ],
            options={
                'ordering': ['template_form'],
            },
        ),
    ]
